  - name: Ensure iApp Service Discovery is configured for web1
    bigip_iapp_service:
        server: "{{ dnsPrefix }}-central.{{ location }}.cloudapp.azure.com"
        validate_certs: False
        user: "{{ adminUsername }}"
        password: "{{ adminPassword }}"
        template: f5.service_discovery
        name: azure-web1
        parameters:
            variables:
                - name: cloud__azure_client_id
                  value: "{{ servicePrincipal }}"
                - name: cloud__azure_resource_group
                  value: "{{ groupPrefix }}-web1"
                - name: cloud__azure_sp_secret
                  value: "{{ clientSecret }}"
                - name: cloud__azure_subscription_id
                  value: "{{ subscriptionId }}"
                - name: cloud__azure_tenant_id
                  value: "{{ tenantId }}"
                - name: cloud__cloud_provider
                  value: azure
                - name: monitor__frequency
                  value: "10"
                - name: monitor__http_method
                  value: GET
                - name: monitor__http_version
                  value: http11
                - name: monitor__monitor
                  value: "/#create_new#"
                - name: monitor__uri
                  value: "/"
                - name: monitor__response
                  value: ""
                - name: pool__interval
                  value: "10"
                - name: pool__member_conn_limit
                  value: "0"
                - name: pool__member_port
                  value: "80"
                - name: pool__pool_to_use
                  value: "/#create_new#"
                - name: pool__public_private
                  value: private
                - name: pool__tag_key
                  value: F5pool
                - name: pool__tag_value
                  value: web1
    delegate_to: localhost

  - name: Ensure iApp Service Discovery is configured for web2
    bigip_iapp_service:
        server: "{{ dnsPrefix }}-central.{{ location }}.cloudapp.azure.com"
        validate_certs: False
        user: "{{ adminUsername }}"
        password: "{{ adminPassword }}"
        template: f5.service_discovery
        name: azure-web2
        parameters:
            variables:
                - name: cloud__azure_client_id
                  value: "{{ servicePrincipal }}"
                - name: cloud__azure_resource_group
                  value: "{{ groupPrefix }}-web2"
                - name: cloud__azure_sp_secret
                  value: "{{ clientSecret }}"
                - name: cloud__azure_subscription_id
                  value: "{{ subscriptionId }}"
                - name: cloud__azure_tenant_id
                  value: "{{ tenantId }}"
                - name: cloud__cloud_provider
                  value: azure
                - name: monitor__frequency
                  value: "10"
                - name: monitor__http_method
                  value: GET
                - name: monitor__http_version
                  value: http11
                - name: monitor__monitor
                  value: "/#create_new#"
                - name: monitor__uri
                  value: "/"
                - name: monitor__response
                  value: ""
                - name: pool__interval
                  value: "10"
                - name: pool__member_conn_limit
                  value: "0"
                - name: pool__member_port
                  value: "80"
                - name: pool__pool_to_use
                  value: "/#create_new#"
                - name: pool__public_private
                  value: private
                - name: pool__tag_key
                  value: F5pool
                - name: pool__tag_value
                  value: web2
    delegate_to: localhost

  - name: Ensure virtual server is configured for web1
    bigip_virtual_server:
        server: "{{ dnsPrefix }}-central.{{ location }}.cloudapp.azure.com"
        validate_certs: False
        user: "{{ adminUsername }}"
        password: "{{ adminPassword }}"
        name: azure-web1
        destination: 10.0.20.11
        port: 80
        pool: /Common/azure-web1.app/azure-web1_pool
        snat: None
        description: This is virtual server for web1 app in Azure
        all_profiles:
            - http
    delegate_to: localhost

  - name: Ensure virtual server is configured for web2
    bigip_virtual_server:
        server: "{{ dnsPrefix }}-central.{{ location }}.cloudapp.azure.com"
        validate_certs: False
        user: "{{ adminUsername }}"
        password: "{{ adminPassword }}"
        name: azure-web2
        destination: 10.0.20.12
        port: 80
        pool: /Common/azure-web2.app/azure-web2_pool
        snat: None
        description: This is virtual server for web2 app in Azure
        all_profiles:
            - http
    delegate_to: localhost

  - name: Wait for web1 to become accessible on public endpoint
    uri:
      url: "http://app1.{{ groupPrefix }}.azure.tomaskubica.cz"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 120
    delay: 1
    delegate_to: localhost

  - name: Wait for web2 to become accessible on public endpoint
    uri:
      url: "http://app2.{{ groupPrefix }}.azure.tomaskubica.cz"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 120
    delay: 1
    delegate_to: localhost
