- name: F5 and Azure demo playbook
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    location: westeurope
    centralNetName: centralNet
    onpremNetName: onpremNet
    adminUsername: tomas
    adminPassword: Azure12345678
    license1: "{{ lookup('env','F5_license1') }}"
    license2: "{{ lookup('env','F5_license2') }}"
    groupPrefix: f5demo
    dnsPrefix: mybigip
  tasks:

  - name: Ensure resource group for Azure central environment exist
    azure_rm_resourcegroup:
      name: "{{ groupPrefix }}-service"
      location: "{{ location }}"

  - name: Ensure Azure central networks exist
    azure_rm_deployment:
      deployment_name: centralNet
      location: "{{ location }}"
      resource_group_name: "{{ groupPrefix }}-service"
      template: "{{ lookup('file', 'netDeploy.json') }}"
      parameters:
        netName: 
          value: "{{ centralNetName }}"
        netPrefix: 
          value: 10.0.0.0/16
        internalPrefix: 
          value: 10.0.10.0/24
        externalPrefix: 
          value: 10.0.20.0/24
        managementPrefix: 
          value: 10.0.30.0/24

  - name: Ensure F5 in central network is deployed
    azure_rm_deployment:
      deployment_name: f5
      location: "{{ location }}"
      resource_group_name: "{{ groupPrefix }}-service"
      template: "{{ lookup('file', 'big-ip-ve-byol-3nic.json') }}"
      parameters:
        adminUsername: 
          value: "{{ adminUsername }}"
        adminPassword:
          value: "{{ adminPassword }}"
        dnsLabel:
          value: "{{ dnsPrefix }}-central"
        instanceName:
          value: "{{ dnsPrefix }}-central"
        instanceType:
          value: Standard_D3_v2
        imageName:
          value: Best
        licenseKey1:
          value: "{{ license1 }}"
        numberOfExternalIps:
          value: 5
        vnetName:
          value: "{{ centralNetName }}"
        vnetResourceGroupName:
          value: "{{ groupPrefix }}-service"
        mgmtSubnetName:
          value: management
        mgmtIpAddress:
          value: 10.0.30.10
        externalSubnetName:
          value: external
        externalIpAddressRangeStart:
          value: 10.0.20.10
        internalSubnetName:
          value: internal
        internalIpAddress:
          value: 10.0.10.10

  - name: Ensure resource group for on-premises demo exist
    azure_rm_resourcegroup:
      name: "{{ groupPrefix }}-onprem"
      location: "{{ location }}"

  - name: Ensure networks for on-premises demo exist
    azure_rm_deployment:
      deployment_name: onpremNet
      location: "{{ location }}"
      resource_group_name: "{{ groupPrefix }}-onprem"
      template: "{{ lookup('file', 'netDeploy.json') }}"
      parameters:
        netName: 
          value: "{{ onpremNetName }}"
        netPrefix: 
          value: 10.128.0.0/16
        internalPrefix: 
          value: 10.128.10.0/24
        externalPrefix: 
          value: 10.128.20.0/24
        managementPrefix: 
          value: 10.128.30.0/24

  - name: Ensure F5 in onpremises is deployed
    azure_rm_deployment:
      deployment_name: f5
      location: "{{ location }}"
      resource_group_name: "{{ groupPrefix }}-onprem"
      template: "{{ lookup('file', 'big-ip-ve-byol-3nic.json') }}"
      parameters:
        adminUsername: 
          value: "{{ adminUsername }}"
        adminPassword:
          value: "{{ adminPassword }}"
        dnsLabel:
          value: "{{ dnsPrefix }}-onprem"
        instanceName:
          value: "{{ dnsPrefix }}-onprem"
        instanceType:
          value: Standard_D3_v2
        imageName:
          value: Best
        licenseKey1:
          value: "{{ license2 }}"
        numberOfExternalIps:
          value: 5
        vnetName:
          value: "{{ onpremNetName }}"
        vnetResourceGroupName:
          value: "{{ groupPrefix }}-onprem"
        mgmtSubnetName:
          value: management
        mgmtIpAddress:
          value: 10.128.30.10
        externalSubnetName:
          value: external
        externalIpAddressRangeStart:
          value: 10.128.20.10
        internalSubnetName:
          value: internal
        internalIpAddress:
          value: 10.128.10.10