- name: F5 and Azure demo playbook
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    location: westeurope
    centralNetName: centralNet
    onpremNetName: onpremNet
    adminUsername: tomas
    adminPassword: Azure12345678
    license1: "{{ lookup('env','F5_LICENSE1') }}"
    license2: "{{ lookup('env','F5_LICENSE2') }}"
    servicePrincipal: "{{ lookup('env','AZURE_CLIENT_ID') }}"
    clientSecret: "{{ lookup('env','AZURE_SECRET') }}"
    tenantId: "{{ lookup('env','AZURE_TENANT') }}"
    groupPrefix: f5demo
    dnsPrefix: mybigip
  tasks:

  - name: Make sure bursting environment with app and iApp Application Connector exists
    include_tasks: bursting.yaml

  - name: TESTING ONLY, to be romoved
    fail:

  - name: Ensure F5 in Azure environment is deployed
    include_tasks: F5inAzure.yaml

  - name: Ensure Azure web servers are deployed
    include_tasks: webServers.yaml

  - name: Ensure F5 on premises (simulated in Azure) is deployed
    include_tasks: F5onPrem.yaml

